name: 'Git Queue'
description: 'A GitHub Action that implements a job queue with a concurrency lock by using Git empty commits'
author: 'Nautilus Cyberneering'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
