name: Publish GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn install && yarn all

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: steps.check-version.outputs.prerelease == 'true'
